apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: myshop/auth
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: auth.env
            - secretRef:
                name: jwt-keys
      restartPolicy: Always
