apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: myshop/product
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: product.env
      restartPolicy: Always
