apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: my-shop
deploy:
  kubectl:
    manifests:
      - infra/k8s/dev/deploys/*.yaml
build:
  local:
    push: false
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:
    - image: myshop/auth
      context: app
      docker:
        dockerfile: Dockerfile.Server.dev
        buildArgs:
          Service: auth
      sync:
        infer:
          - '**/*.ts'
          - '**/*.js'
          - '**/*.map'
    - image: myshop/cart
      context: app
      docker:
        dockerfile: Dockerfile.Server.dev
        buildArgs:
          Service: cart
      sync:
        infer:
          - '**/*.ts'
          - '**/*.js'
          - '**/*.map'
    - image: myshop/product
      context: app
      docker:
        dockerfile: Dockerfile.Server.dev
        buildArgs:
          Service: product
      sync:
        infer:
          - '**/*.ts'
          - '**/*.js'
          - '**/*.map'

    - image: myshop/payment
      context: app
      docker:
        dockerfile: Dockerfile.Server.dev
        buildArgs:
          Service: payment
      sync:
        infer:
          - '**/*.ts'
          - '**/*.js'
          - '**/*.map'

    - image: myshop/client
      context: app
      docker:
        dockerfile: Dockerfile.Client.dev
      sync:
        infer:
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.scss'
