apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: my-shop
deploy:
  kubectl:
    manifests:
      - infra/k8s/dev/*.yaml
build:
  local:
    push: false
    # useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
    - image: myshop/auth
      context: app
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          Service: auth
      sync:
        infer:
          - 'server/services/auth/src/**/*.ts'
          - 'server/packages/**/src/**/*.ts'
          - 'server/services/auth/src/*.ts'
          - 'server/packages/**/src/*.ts'
    - image: myshop/cart
      context: app
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          Service: cart
      sync:
        infer:
          - 'server/services/cart/src/**/*.ts'
          - 'server/packages/**/src/**/*.ts'
          - 'server/services/cart/src/*.ts'
          - 'server/packages/**/src/*.ts'
    - image: myshop/product
      context: app
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          Service: product
      sync:
        infer:
          - 'server/services/product/src/**/*.ts'
          - 'server/packages/**/src/**/*.ts'
          - 'server/services/product/src/*.ts'
          - 'server/packages/**/src/*.ts'

    - image: myshop/payment
      context: app
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          Service: payment
      sync:
        infer:
          - 'server/services/payment/src/**/*.ts'
          - 'server/packages/**/src/**/*.ts'
          - 'server/services/payment/src/*.ts'
          - 'server/packages/**/src/*.ts'

    - image: myshop/client
      context: app/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.jsx'
            dest: .
          - src: 'src/**/*.scss'
            dest: .
