apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  labels:
    app: verdaccio-config
data:
  config.yaml: |-
    storage: /verdaccio/storage
    max_body_size: 1000mb
    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd

    uplinks:
      npmjs:
        url: https://registry.npmjs.org/

    packages:
      '@*/*':
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: npmjs

    middlewares:
      audit:
        enabled: true
    logs:
      - {type: stdout, format: pretty, level: debug}

    security:
      legacy: true
      api:
        jwt:
          sign:
            expiresIn: 7d
            notBefore: 0
      web:
        sign:
          expiresIn: 7d
        enable: true
        title: 'My-shop\'s registry'
        primary_color: "#4b5e40"
        gravatar: true | false
        scope: "@my-shop"
        sort_packages: asc | desc
        darkMode: true