version: 2.1
orbs:
  win: circleci/windows@2.4.0
commands:
  update-yarn:
    steps:
      - run:
          name: Update yarn
          command: yarn global add yarn@latest
  install:
    steps:
      - run:
          name: Install dependencies
          command: yarn --immutable --ignore-engines
  audit:
    steps:
      - run:
          name: Audit dependencies
          command: yarn audit
  lint:
    steps:
      - run:
          name: Lint app
          command: yarn lint
  build-packages:
    steps:
      - run:
          name: Build packages
          command: yarn build:changed
  test:
    steps:
      - run:
          name: Test
          command: yarn test-ci
  save-cache:
    steps:
      - save_cache:
          key: v1-my-shop-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  run-build-n-test:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-my-shop-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
      - update-yarn
      - install
      - save-cache
      - lint
      - build-packages
      - test
jobs:
  test-node12:
    docker:
      - image: node:12
    steps:
      - run-build-n-test
  test-node14:
    docker:
      - image: node:14
    steps:
      - run-build-n-test
  test-node15:
    docker:
      - image: node:15
    steps:
      - run-build-n-test
  test-windows:
    executor: win/default
    steps:
      - run-build-n-test

workflows:
  Build-Test:
    jobs:
      - test-node12:
          filters:
            branches:
              ignore:
                - master
                - prerelease
      - test-node14:
          filters:
            branches:
              ignore:
                - master
                - prerelease
      - test-node15:
          filters:
            branches:
              ignore:
                - master
                - prerelease
      - test-windows:
          filters:
            branches:
              ignore:
                - master
                - prerelease
