FROM node:15-alpine

WORKDIR /usr/src/app

ARG Service

COPY services/${Service}/package.json .
COPY packages/common/package.json packages/common/package.json
RUN yarn

COPY services/${Service}/src src
COPY typings/server src/@types
COPY packages/common/build packages/common/build


COPY tsconfig.Server.json ./tsconfig.build.json
COPY nodemon.json .


CMD [ "yarn", "dev" ]