FROM node:15-alpine

WORKDIR /usr/src/app

COPY client/package.json ./package.json
RUN yarn

COPY client/src ./src/
COPY client/public ./public/
COPY tsconfig.Client.json ./tsconfig.json

CMD ["yarn", "start"]