FROM node:15-alpine

WORKDIR /usr/src/app

ARG Service

COPY tsconfig.build.json .
COPY nodemon.json .
COPY @types ./@types
COPY server/services/${Service}/src src
COPY server/services/${Service}/package.json .

COPY server/packages/common/build packages/common/build
COPY server/packages/common/package.json packages/common/package.json

RUN yarn

CMD [ "yarn", "dev" ]