FROM node:15-alpine

WORKDIR /usr/src/app

ARG Service

COPY server/services/${Service}/package.json .
COPY server/packages/common/package.json packages/common/package.json
RUN yarn

COPY server/services/${Service}/src src
COPY server/@types src/@types
COPY server/packages/common/build packages/common/build


COPY tsconfig.Server.json ./tsconfig.build.json
COPY nodemon.json .


CMD [ "yarn", "dev" ]