FROM node:15-alpine

WORKDIR /usr/src/app

COPY services/client/package.json ./package.json
RUN yarn

COPY services/client/public ./public/
COPY typings/client ./src/@types
COPY services/client/src ./src/

COPY tsconfig.Client.json ./tsconfig.json

CMD ["yarn", "start"]