FROM node:15-alpine

WORKDIR /usr/src/app

ARG Service

RUN chown -R node:node /usr/src/app

USER node

COPY --chown=node:node services/${Service}/package.json .
COPY --chown=node:node packages/common/package.json packages/common/package.json
RUN  yarn --production

COPY --chown=node:node services/${Service}/build build
COPY --chown=node:node packages/common/build packages/common/build

CMD [ "yarn", "start" ]