export const userActionTypes = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  CHECK_TOKEN: 'CHECK_TOKEN',
  LOGOUT_USER: 'LOGOUT_USER'
};
