export const userActionTypes = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',
  LOGOUT_USER: 'LOGOUT_USER',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_ERROR: 'GET_PROFILE_ERROR',
  GET_PROFILE: 'GET_PROFILE',
  LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED'

};
