export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  FETCH_CART: 'FETCH_CART',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_ERROR: 'FETCH_CART_ERROR',
  PUSH_TO_CART: 'PUSH_TO_CART',
  PUSH_TO_CART_ERROR: 'PUSH_TO_CART_ERROR',
  MAKE_PAYMENT: 'MAKE_PAYMENT',
  MAKE_PAYMENT_SUCCESS: 'MAKE_PAYMENT_SUCCESS',
  MAKE_PAYMENT_ERROR: 'MAKE_PAYMENT_ERROR'
};
