name: Common Package CD

on:
  push:
    branches: [common-package, common-package-next, common-package-alpha]
    paths: 
      - "server/packages/common/**"
jobs:
  publish-common-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "server/packages/common"
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Get version from package.json before release step
      id: currentVersion
      run: echo "::set-output name=version::$(npm run get:version --silent)"
    - name: Build Package
      run: npm run build
    - name: Release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: \@my-shop-bot
        GIT_AUTHOR_EMAIL: bot@my-shop.com
        GIT_COMMITTER_NAME: \@my-shop-bot
        GIT_COMMITTER_EMAIL: bot@my-shop.com
      run: npm run release
    - name: Get version from package.json after release step
      id: releasedVersion
      run: echo "::set-output name=version::$(npm run get:version --silent)"
    - name: Create Pull Request with updated package files
      if: steps.currentVersion.outputs.version != steps.releasedVersion.outputs.version
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: 'chore(common package release): ${{ steps.releasedVersion.outputs.version }}'
        committer: \@my-shop-bot <bot@my-shop.com>
        author: \@my-shop-bot <bot@my-shop.com>
        title: 'chore(common package release): ${{ steps.releasedVersion.outputs.version }}'
        body: 'Version bump in package.json and package-lock.json for release [${{ steps.releasedVersion.outputs.version }}](https://github.com/${{github.repository}}/releases/tag/@my-shop/common-v${{ steps.releasedVersion.outputs.version }})'
        branch: version-bump/common-package/${{ steps.releasedVersion.outputs.version }}