name: Automerge common package release bump PR

on:
  pull_request:
    branches: [common-package, common-package-next, common-package-alpha]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite: 
    types:
      - completed
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == "@my-shop-bot"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-merge:
    needs: [auto-approve]
    runs-on: ubuntu-latest
    steps:
      - name: Auto merging
        uses: pascalgn/automerge-action@v0.13.1
        if: github.actor == "@my-shop-bot"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          GITHUB_LOGIN: "@my-shop-bot"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"