name: Release Workflow

on:
  push:
    branches: [master, prerelease]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 15
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn --immutable
      - name: PreRelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "github.ref == 'refs/heads/prerelease'"
        run: yarn pre-release
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "github.ref == 'refs/heads/master'"
        run: yarn release
